/**
 * Central type definitions shared across the application.
 * Keeping these in one place avoids duplicate/near-duplicate shapes
 * across services.
 */

import z from "zod";
import { videoMetadataSchema } from "../services/gemini/metadataSchema.js";

export type UploadStatus =
  | 'pending'
  | 'generating_metadata'
  | 'uploading'
  | 'uploaded'
  | 'failed';

export type PrivacyStatus = 'private' | 'public' | 'unlisted';

/** A row in the `uploads` SQLite table. */
export interface UploadRecord {
  id: number;
  filename: string;
  fileHash: string | null;
  youtubeVideoId: string | null;
  title: string | null;
  description: string | null;
  status: UploadStatus;
  scheduledTime: string | null;
  uploadedAt: string | null;
  createdAt: string;
  error: string | null;
}

export type NewUploadRecord = Pick<UploadRecord, 'filename' | 'fileHash' | 'status'>;

/** Structured metadata generated by Gemini for a single video. */
export type VideoMetadata = z.infer<typeof videoMetadataSchema>;

/** A video file discovered on disk, waiting to be processed. */
export interface DiscoveredVideo {
  filename: string;
  absolutePath: string;
  extension: string;
  sizeBytes: number;
  createdAt: Date;
}

/** Result of a single YouTube upload attempt. */
export interface UploadResult {
  youtubeVideoId: string;
  privacyStatus: PrivacyStatus;
  scheduledPublishAt: string | null;
}

/** Options controlling how a video should be published. */
export interface UploadOptions {
  privacyStatus: PrivacyStatus;
  categoryId: string;
  publishAt?: string; // RFC3339 timestamp for scheduled uploads
}

export class AppError extends Error {
  public readonly code: string;
  public readonly cause?: unknown;

  constructor(message: string, code: string, cause?: unknown) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.cause = cause;
  }
}

export class MetadataGenerationError extends AppError {
  constructor(message: string, cause?: unknown) {
    super(message, 'METADATA_GENERATION_ERROR', cause);
    this.name = 'MetadataGenerationError';
  }
}

export class YouTubeUploadError extends AppError {
  public readonly isQuotaError: boolean;
  public readonly isTransient: boolean;

  constructor(message: string, options: { isQuotaError?: boolean; isTransient?: boolean; cause?: unknown } = {}) {
    super(message, 'YOUTUBE_UPLOAD_ERROR', options.cause);
    this.name = 'YouTubeUploadError';
    this.isQuotaError = options.isQuotaError ?? false;
    this.isTransient = options.isTransient ?? false;
  }
}

export class StorageError extends AppError {
  constructor(message: string, cause?: unknown) {
    super(message, 'STORAGE_ERROR', cause);
    this.name = 'StorageError';
  }
}

export class DatabaseError extends AppError {
  constructor(message: string, cause?: unknown) {
    super(message, 'DATABASE_ERROR', cause);
    this.name = 'DatabaseError';
  }
}

export interface MetadataBlacklist {
  recentTitles: string[];
  recentDescriptionOpenings: string[];
  recentCTAs: string[];
}
